title: WrapChiQ®
owner: n00kl33r
email:
description: Website for shop!
url: https://wrapchiq.github.io # the base hostname & protocol for your site, e.g. http://example.com
language: en

# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
